name: sugar_meter
description: Sugar meter flutter app

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  #https://pub.dev/packages/firebase_core
  firebase_core: 1.4.0
  #https://pub.dev/packages/firebase_auth
  firebase_auth: ^3.0.1
  #https://pub.dev/packages/flutter_bloc
  flutter_bloc: ^7.1.0
  #https://pub.dev/packages/google_sign_in
  google_sign_in: ^5.0.3
  #https://pub.dev/packages/flutter_login_facebook
  flutter_login_facebook: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/images/